server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:sa
    username: sa
    password:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enable: true
      path: /banco
      settings:
        trace: false
        web-allow-others: true